import logging
from typing import Dict, Any

from src.core.state import PRAnalysisState
from src.utils.azure_requests import AzureManager

logger = logging.getLogger(__name__)


def publish_comments_node(state: PRAnalysisState) -> Dict[str, Any]:
    logger.info("[NODE: publish_comments] Starting comment publication to Azure DevOps")

    pr_id = state.get("pr_id")

    if not pr_id:
        logger.error("[NODE: publish_comments] ❌ No PR ID found in state")
        return {
            "error": "No PR ID available for publishing comments"
        }

    final_comments = state.get("final_comments")

    if not final_comments:
        logger.warning("[NODE: publish_comments] ⚠️ No final comments found to publish")
        return {
            "publication_stats": {
                "total_comments": 0,
                "successful": 0,
                "failed": 0,
                "message": "No final comments to publish"
            }
        }

    comments = final_comments

    if not comments:
        logger.info("[NODE: publish_comments] No comments generated by reviewer")
        return {
            "publication_stats": {
                "total_comments": 0,
                "successful": 0,
                "failed": 0,
                "message": "No comments to publish"
            }
        }

    logger.info(
        f"[NODE: publish_comments] Publishing {len(comments)} comment(s) "
        f"from reviewer analysis"
    )

    publication_stats = AzureManager.publish_analysis_comments(
        pr_id=pr_id,
        comments=comments
    )

    published_comments_list = publication_stats.get("published_comments", [])

    logger.info(
        f"[NODE: publish_comments] ✅ Publication complete: "
        f"{publication_stats['successful']}/{publication_stats['total_comments']} "
        f"comments published successfully"
    )

    if publication_stats['failed'] > 0:
        logger.warning(
            f"[NODE: publish_comments] ⚠️ {publication_stats['failed']} comments "
            f"failed to publish"
        )
        for error in publication_stats.get('errors', []):
            logger.debug(f"[NODE: publish_comments] Error detail: {error}")

    return {
        "published_comments": published_comments_list
    }